server:
  port: 7700
spring:
  boot:
    admin:
      context-path: /admin-server
  application:
    name: admin-server
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
